Feature/wheel
miloserdova-l/mrob pull request #1
Opened 2020-12-15 21:32 UTC by miloserdova-l

Added building wheel for Linux and configured automatic release.

2020-12-17 13:05 UTC, iakov requested changes

2020-12-17 13:05 UTC, iakov commented on Dockerfile
> +ADD ./scripts/build-cmake.sh /scripts/build-cmake.sh
Основное замечание к докеру: надо сделать всё одной командой. и отставить, и почистить. Тогда будет один layer.

2020-12-17 13:05 UTC, iakov commented on Dockerfile
> +
Вообще, есть ощущение, что тут и докер для сборки пакета и сама сборка пакета происходят в одном контейнере.
Где-то тут закончили строить контейнер, в котором всё готово для сборки пакета. И вот этот вот контейнер надо переиспользовать для пересборки колёс. А сами шаги сборки колёс должны быть частью CI.

2020-12-17 13:05 UTC, iakov commented on Dockerfile
> +ADD __init__.py /root/soft/wheel/mrob/__init__.py
Если нормально порефакторить Докер и CI, вот этого ужаса с копированием файлов внутрь докера не будет. Это всё не надо, эти команды должны выполняться в контейнере, но не при сборке контейнера.

2020-12-17 13:05 UTC, iakov commented on scripts/build-wheels.sh
> +LATEST=""
Такие вспомогательные скрипты желательно писать так, чтобы можно было их локально и на разных CI переиспользовать.

2020-12-17 13:05 UTC, iakov commented on scripts/clone-mrob.sh
> +#!/bin/bash
Это должно просто перейти в CI

2020-12-17 20:44 UTC, miloserdova-l commented on Dockerfile
> +ADD ./scripts/build-cmake.sh /scripts/build-cmake.sh
Сделано.

2020-12-18 11:11 UTC, iakov requested changes

2020-12-18 11:11 UTC, iakov commented on .circleci/config.yml
> +      - checkout
Это мы берём все исходники, полный checkout

2020-12-18 11:11 UTC, iakov commented on .circleci/config.yml
> +          command: |
Ок, докерфайл для сборки колёс мы храним в том же репо и совместно сопровождаем, поэтому вынуждены каждый раз пересобирать и делать push. Пусть пока так.

2020-12-18 11:11 UTC, iakov commented on .circleci/config.yml
> +             mkdir ~/soft/mrob/build
А вот это зачем? Зачем мы копируем куда-то? Может быть, нужно сразу туда сделать checkout?

2020-12-18 11:11 UTC, iakov commented on .circleci/config.yml
> +      - build-wheel:
Возможно, не стоит пытаться собирать образ, если обычная простая сборка и базовые тесты какие-нибудь завалены.

2020-12-22 06:08 UTC, miloserdova-l commented on .circleci/config.yml
> +             mkdir ~/soft/mrob/build
Исправлено.

2020-12-22 06:08 UTC, miloserdova-l commented on .circleci/config.yml
> +      - build-wheel:
Исправлено.

2020-12-24 10:18 UTC, iakov requested changes
Я пока не понял, зачем нужны `~/soft/wheel` и `~/soft/mrob`. Возможно, если чуть почистить, получится обойтись без них.

2020-12-24 10:18 UTC, iakov commented on .circleci/config.yml
> +      - checkout
Наверное, у чекаута есть опция, чтобы рекурсивно взять субмодули. Обычно есть.

2020-12-24 10:18 UTC, iakov commented on .circleci/config.yml
> +             git submodule update --init --recursive
Вот эта команда вряд ли нужна, наверное, это через опцию чекаута делается.

2020-12-24 10:18 UTC, iakov commented on .circleci/config.yml
> +             mkdir ~/soft/mrob/build
Наверное, этот каталог можно создавать не на этом шаге, а там, где он реально нужен.

2020-12-24 10:18 UTC, iakov commented on .circleci/config.yml
> +          command: /bin/bash ./scripts/build-wheels.sh
Наверное, не хватает атрибута "исполняемый" у скрипта. Странно, что надо вызывать `bash`, а не просто скрипт.

2020-12-24 10:18 UTC, iakov commented on .circleci/config.yml
> +          command: cp -a ~/soft/wheel/dist ~/artifacts
Зачем? Почему нельзя сразу этот каталог под правильным именем сохранять в store_artifacts?

2020-12-26 13:10 UTC, miloserdova-l commented on .circleci/config.yml
> +          command: /bin/bash ./scripts/build-wheels.sh
Исправлено.

2020-12-26 13:10 UTC, miloserdova-l commented on .circleci/config.yml
> +          command: cp -a ~/soft/wheel/dist ~/artifacts
Исправлено.

2020-12-26 13:11 UTC, miloserdova-l commented on .circleci/config.yml
> +             mkdir ~/soft/mrob/build
Исправлено.

2020-12-26 13:14 UTC, miloserdova-l commented on .circleci/config.yml
> +             git submodule update --init --recursive
С официального сайта: CircleCI does not check out submodules. If your project requires submodules, add run steps with appropriate commands

2020-12-26 16:37 UTC, iakov requested changes

2020-12-26 16:37 UTC, iakov commented on .circleci/config.yml
> +             chmod +x ./scripts/build-wheels.sh
Это тут не надо, надо просто в гит выложить файл с атрибутом.

2020-12-26 16:37 UTC, iakov commented on scripts/build-wheels.sh
> +mkdir ./build
`cd $(dirname $(realpath "${BASH_SOURCE[0]}"))`

2020-12-26 16:37 UTC, iakov commented on scripts/build-wheels.sh
> +mkdir ./build
`set -euo pipefail`

2020-12-26 16:37 UTC, iakov commented on scripts/build-wheels.sh
> +
export LC_ALL=C

2020-12-26 16:37 UTC, iakov commented on scripts/build-wheels.sh
> +    mv ../lib/* ../mrob
Wow!

2020-12-26 16:37 UTC, iakov commented on scripts/build-wheels.sh
> +chrpath -r '$ORIGIN' ../mrob/mrob.*.so
auditwheel?

2020-12-31 14:04 UTC, miloserdova-l commented on scripts/build-wheels.sh
> +mkdir ./build
Добавлено

2020-12-31 14:04 UTC, miloserdova-l commented on scripts/build-wheels.sh
> +
Добавлено

2021-01-13 11:39 UTC, iakov approved these changes

2021-01-14 15:14 UTC, merged